// $(document).ready(function() {
//     $(".BaijuDefaulState").hover(function() {
//       $(this).find(".Baiju").css("height", "100%");
//     }, function() {
//       $(this).find(".Baiju").css("height", "0%");
//     });
//   });
// const textFind = document.getElementById("Component21TextFind");
// const photoGroup = document.getElementById("PhotoGroup128");

// textFind.addEventListener("mouseover", function() {
//     photoGroup.style.backgroundImage = "url('Home/Group\ 267.png')";
// });

// textFind.addEventListener("mouseout", function() {
//     photoGroup.style.backgroundImage = "url('Home/Group128.png')";
// });



